default: &default
  adapter: postgresql
  encoding: unicode
  username: clintonjacos
  password: Clinton@1234
  host: localhost
  pool: 5
  port: 5432

development:
  <<: *default
  database: my_firstApp_ruby_development

test:
  <<: *default
  database: my_firstApp_ruby_test

production:
  <<: *default
  database: my_firstApp_ruby_development
  username: clintonjacos
  password: <%= ENV['MY_FIRSTAPP_RUBY_DATABASE_PASSWORD'] %>